# Assignment 1

In [1]:
import numpy as np

%load_ext autoreload
%autoreload 2

## 1 Softmax

In [2]:
!python q1_softmax.py

Running basic tests...
[ 0.26894142  0.73105858]
[[ 0.26894142  0.73105858]
 [ 0.26894142  0.73105858]]
[[ 0.73105858  0.26894142]]
You should be able to verify these results by hand!

Running your tests...


## 2 Neural Network Basics

In [3]:
!python q2_sigmoid.py

Running basic tests...
[[ 0.73105858  0.88079708]
 [ 0.26894142  0.11920292]]
[[ 0.19661193  0.10499359]
 [ 0.19661193  0.10499359]]
You should verify these results by hand!

Running your tests...


In [4]:
!python q2_gradcheck.py

Running sanity checks...
Gradient check passed!
Gradient check passed!
Gradient check passed!

Running your sanity checks...


In [5]:
!python q2_neural.py

Running sanity check...
Gradient check passed!
Running your sanity checks...


## 3 word2vec

In [6]:
!python q3_word2vec.py

Testing normalizeRows...
[[ 0.6         0.8       ]
 [ 0.4472136   0.89442719]]

==== Gradient check for skip-gram ====
Gradient check passed!
Gradient check passed!

==== Gradient check for CBOW      ====
Gradient check passed!
Gradient check passed!

=== Results ===
(11.166109001533981, array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-1.26947339, -1.36873189,  2.45158957],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]]), array([[-0.41045956,  0.18834851,  1.43272264],
       [ 0.38202831, -0.17530219, -1.33348241],
       [ 0.07009355, -0.03216399, -0.24466386],
       [ 0.09472154, -0.04346509, -0.33062865],
       [-0.13638384,  0.06258276,  0.47605228]]))
(13.959405258751875, array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [-4.12113804, -1.67347865, -1.5049951 ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.  

In [7]:
!python q3_sgd.py

Running sanity checks...
iter 100: 0.004578
iter 200: 0.004353
iter 300: 0.004136
iter 400: 0.003929
iter 500: 0.003733
iter 600: 0.003546
iter 700: 0.003369
iter 800: 0.003200
iter 900: 0.003040
iter 1000: 0.002888
test 1 result: 8.41483678608e-10
iter 100: 0.000000
iter 200: 0.000000
iter 300: 0.000000
iter 400: 0.000000
iter 500: 0.000000
iter 600: 0.000000
iter 700: 0.000000
iter 800: 0.000000
iter 900: 0.000000
iter 1000: 0.000000
test 2 result: 0.0
iter 100: 0.041205
iter 200: 0.039181
iter 300: 0.037222
iter 400: 0.035361
iter 500: 0.033593
iter 600: 0.031913
iter 700: 0.030318
iter 800: 0.028802
iter 900: 0.027362
iter 1000: 0.025994
test 3 result: -2.52445103582e-09

Running your sanity checks...


In [2]:
!python q3_run.py

iter 10: 22.721348
iter 20: 22.561229
iter 30: 22.492990
iter 40: 22.481537
iter 50: 22.386783
iter 60: 22.449259
iter 70: 22.455238
iter 80: 22.483793
iter 90: 22.449923
iter 100: 22.356749
iter 110: 22.329225
iter 120: 22.181088
iter 130: 22.330100
iter 140: 22.250549
iter 150: 22.037723
iter 160: 21.988025
iter 170: 21.917943
iter 180: 21.805616
iter 190: 21.897164
iter 200: 21.839254
iter 210: 21.868112
iter 220: 21.872646
iter 230: 21.907447
iter 240: 21.925275
iter 250: 21.881191
iter 260: 21.885078
iter 270: 22.041265
iter 280: 22.235377
iter 290: 22.221542
iter 300: 22.231273
iter 310: 22.217637
iter 320: 22.219967
iter 330: 22.229784
iter 340: 21.995119
iter 350: 21.939931
iter 360: 22.062884
iter 370: 22.095802
iter 380: 22.127087
iter 390: 22.164447
iter 400: 22.268542
iter 410: 22.329292
iter 420: 22.356539
iter 430: 22.382393
iter 440: 22.391705
iter 450: 22.446303
iter 460: 22.238907
iter 470: 22.293520
iter 480: 22.368290
iter 490: 22.241100
iter 500: 22.196496
iter 510:

iter 3970: 19.502017
iter 3980: 19.413491
iter 3990: 19.506804
iter 4000: 19.302633
iter 4010: 19.277788
iter 4020: 19.348366
iter 4030: 19.411653
iter 4040: 19.378502
iter 4050: 19.394461
iter 4060: 19.269716
iter 4070: 19.218330
iter 4080: 19.125327
iter 4090: 19.269999
iter 4100: 19.152700
iter 4110: 19.124942
iter 4120: 19.148848
iter 4130: 19.122105
iter 4140: 19.153196
iter 4150: 19.132451
iter 4160: 19.088310
iter 4170: 19.017308
iter 4180: 19.040485
iter 4190: 19.005247
iter 4200: 18.985783
iter 4210: 18.972086
iter 4220: 19.004663
iter 4230: 18.991102
iter 4240: 19.112587
iter 4250: 19.094492
iter 4260: 19.075782
iter 4270: 19.036095
iter 4280: 18.946679
iter 4290: 18.980200
iter 4300: 19.029955
iter 4310: 18.964510
iter 4320: 19.038665
iter 4330: 19.035170
iter 4340: 19.072679
iter 4350: 19.003197
iter 4360: 18.979269
iter 4370: 18.903816
iter 4380: 18.758706
iter 4390: 18.871687
iter 4400: 18.909462
iter 4410: 18.857609
iter 4420: 18.822238
iter 4430: 18.748321
iter 4440: 18

iter 7880: 14.633986
iter 7890: 14.575429
iter 7900: 14.528745
iter 7910: 14.559128
iter 7920: 14.572236
iter 7930: 14.495554
iter 7940: 14.397428
iter 7950: 14.408780
iter 7960: 14.330179
iter 7970: 14.360329
iter 7980: 14.331491
iter 7990: 14.412557
iter 8000: 14.437714
iter 8010: 14.394935
iter 8020: 14.306785
iter 8030: 14.325389
iter 8040: 14.274469
iter 8050: 14.171190
iter 8060: 14.270733
iter 8070: 14.303221
iter 8080: 14.412160
iter 8090: 14.364430
iter 8100: 14.319825
iter 8110: 14.341182
iter 8120: 14.212112
iter 8130: 14.303821
iter 8140: 14.232270
iter 8150: 14.177477
iter 8160: 14.062216
iter 8170: 14.090100
iter 8180: 14.099282
iter 8190: 14.157185
iter 8200: 14.161839
iter 8210: 14.140375
iter 8220: 14.194521
iter 8230: 14.156269
iter 8240: 14.194285
iter 8250: 14.159525
iter 8260: 14.191953
iter 8270: 14.128510
iter 8280: 14.144264
iter 8290: 14.083933
iter 8300: 14.138485
iter 8310: 14.195829
iter 8320: 14.083229
iter 8330: 14.160219
iter 8340: 14.138532
iter 8350: 14

iter 11710: 11.980584
iter 11720: 11.984932
iter 11730: 11.974965
iter 11740: 12.020777
iter 11750: 12.121345
iter 11760: 12.101180
iter 11770: 12.063188
iter 11780: 12.022902
iter 11790: 12.085324
iter 11800: 11.983840
iter 11810: 12.014503
iter 11820: 12.028442
iter 11830: 12.050638
iter 11840: 11.964854
iter 11850: 11.999369
iter 11860: 11.925020
iter 11870: 11.884194
iter 11880: 11.903817
iter 11890: 11.811934
iter 11900: 11.815928
iter 11910: 11.842900
iter 11920: 11.871880
iter 11930: 11.833781
iter 11940: 11.762665
iter 11950: 11.705261
iter 11960: 11.692142
iter 11970: 11.740968
iter 11980: 11.775563
iter 11990: 11.847638
iter 12000: 11.878289
iter 12010: 11.872838
iter 12020: 11.806588
iter 12030: 11.913348
iter 12040: 11.926810
iter 12050: 11.922906
iter 12060: 11.890822
iter 12070: 11.918037
iter 12080: 11.872137
iter 12090: 11.812248
iter 12100: 11.805471
iter 12110: 11.862988
iter 12120: 11.800322
iter 12130: 11.723925
iter 12140: 11.683016
iter 12150: 11.709907
iter 12160

iter 15440: 11.113496
iter 15450: 11.221503
iter 15460: 11.212374
iter 15470: 11.169557
iter 15480: 11.113421
iter 15490: 11.034585
iter 15500: 11.011152
iter 15510: 11.065778
iter 15520: 11.074962
iter 15530: 11.050286
iter 15540: 10.937364
iter 15550: 10.980510
iter 15560: 11.005018
iter 15570: 11.031625
iter 15580: 11.074769
iter 15590: 11.029936
iter 15600: 10.971251
iter 15610: 10.998689
iter 15620: 10.960645
iter 15630: 10.930938
iter 15640: 10.891617
iter 15650: 10.955229
iter 15660: 11.005636
iter 15670: 10.951131
iter 15680: 10.910765
iter 15690: 10.888678
iter 15700: 10.806516
iter 15710: 10.748858
iter 15720: 10.821909
iter 15730: 10.752542
iter 15740: 10.800892
iter 15750: 10.816737
iter 15760: 10.861567
iter 15770: 10.808359
iter 15780: 10.799645
iter 15790: 10.763563
iter 15800: 10.796761
iter 15810: 10.776988
iter 15820: 10.734242
iter 15830: 10.723814
iter 15840: 10.738877
iter 15850: 10.810514
iter 15860: 10.809872
iter 15870: 10.915820
iter 15880: 10.915136
iter 15890

iter 19170: 10.264559
iter 19180: 10.257168
iter 19190: 10.298949
iter 19200: 10.284028
iter 19210: 10.305832
iter 19220: 10.311613
iter 19230: 10.268154
iter 19240: 10.307193
iter 19250: 10.263235
iter 19260: 10.278955
iter 19270: 10.232017
iter 19280: 10.211022
iter 19290: 10.174205
iter 19300: 10.172232
iter 19310: 10.151155
iter 19320: 10.120080
iter 19330: 10.155058
iter 19340: 10.125108
iter 19350: 10.146431
iter 19360: 10.160341
iter 19370: 10.078186
iter 19380: 10.100024
iter 19390: 10.061894
iter 19400: 10.069655
iter 19410: 10.057138
iter 19420: 10.120438
iter 19430: 10.159270
iter 19440: 10.259560
iter 19450: 10.310653
iter 19460: 10.304996
iter 19470: 10.307068
iter 19480: 10.352141
iter 19490: 10.350919
iter 19500: 10.304820
iter 19510: 10.336477
iter 19520: 10.292861
iter 19530: 10.352412
iter 19540: 10.308787
iter 19550: 10.299722
iter 19560: 10.209843
iter 19570: 10.201729
iter 19580: 10.212818
iter 19590: 10.233188
iter 19600: 10.216513
iter 19610: 10.223853
iter 19620

iter 22930: 9.824150
iter 22940: 9.799997
iter 22950: 9.775664
iter 22960: 9.841692
iter 22970: 9.832681
iter 22980: 9.838378
iter 22990: 9.923440
iter 23000: 9.949199
iter 23010: 9.982451
iter 23020: 9.986211
iter 23030: 9.987852
iter 23040: 9.975941
iter 23050: 9.938696
iter 23060: 9.949176
iter 23070: 9.928097
iter 23080: 9.976305
iter 23090: 9.998490
iter 23100: 9.975541
iter 23110: 9.951372
iter 23120: 9.958265
iter 23130: 10.035894
iter 23140: 9.976866
iter 23150: 9.957089
iter 23160: 9.953049
iter 23170: 9.981655
iter 23180: 9.964364
iter 23190: 10.056125
iter 23200: 10.056988
iter 23210: 10.026824
iter 23220: 9.973965
iter 23230: 9.898222
iter 23240: 9.903991
iter 23250: 9.833825
iter 23260: 9.864268
iter 23270: 9.900083
iter 23280: 9.851682
iter 23290: 9.899587
iter 23300: 9.923156
iter 23310: 9.933397
iter 23320: 9.877514
iter 23330: 9.931332
iter 23340: 9.859689
iter 23350: 9.906013
iter 23360: 9.917057
iter 23370: 9.859891
iter 23380: 9.911202
iter 23390: 9.956827
iter 2340

iter 26800: 9.699748
iter 26810: 9.715920
iter 26820: 9.668903
iter 26830: 9.640979
iter 26840: 9.743227
iter 26850: 9.681427
iter 26860: 9.663645
iter 26870: 9.700461
iter 26880: 9.720468
iter 26890: 9.758713
iter 26900: 9.790362
iter 26910: 9.763262
iter 26920: 9.725559
iter 26930: 9.726401
iter 26940: 9.715479
iter 26950: 9.701067
iter 26960: 9.662093
iter 26970: 9.623516
iter 26980: 9.575152
iter 26990: 9.560240
iter 27000: 9.537594
iter 27010: 9.521825
iter 27020: 9.580288
iter 27030: 9.653100
iter 27040: 9.621663
iter 27050: 9.600247
iter 27060: 9.570072
iter 27070: 9.558244
iter 27080: 9.566340
iter 27090: 9.519884
iter 27100: 9.506050
iter 27110: 9.501727
iter 27120: 9.488330
iter 27130: 9.543435
iter 27140: 9.516338
iter 27150: 9.545366
iter 27160: 9.540497
iter 27170: 9.548034
iter 27180: 9.532633
iter 27190: 9.591617
iter 27200: 9.622033
iter 27210: 9.635755
iter 27220: 9.666242
iter 27230: 9.652999
iter 27240: 9.678363
iter 27250: 9.617845
iter 27260: 9.621534
iter 27270: 9

iter 30700: 9.577844
iter 30710: 9.554299
iter 30720: 9.546138
iter 30730: 9.509178
iter 30740: 9.594445
iter 30750: 9.588757
iter 30760: 9.670677
iter 30770: 9.647942
iter 30780: 9.574842
iter 30790: 9.585866
iter 30800: 9.546640
iter 30810: 9.503495
iter 30820: 9.464836
iter 30830: 9.502221
iter 30840: 9.542706
iter 30850: 9.501824
iter 30860: 9.499891
iter 30870: 9.440808
iter 30880: 9.524934
iter 30890: 9.503906
iter 30900: 9.453452
iter 30910: 9.508248
iter 30920: 9.508683
iter 30930: 9.530128
iter 30940: 9.583529
iter 30950: 9.581817
iter 30960: 9.591893
iter 30970: 9.607849
iter 30980: 9.638651
iter 30990: 9.660350
iter 31000: 9.719782
iter 31010: 9.723245
iter 31020: 9.713387
iter 31030: 9.668768
iter 31040: 9.681209
iter 31050: 9.680502
iter 31060: 9.665414
iter 31070: 9.705372
iter 31080: 9.674521
iter 31090: 9.713707
iter 31100: 9.710632
iter 31110: 9.763219
iter 31120: 9.720317
iter 31130: 9.670659
iter 31140: 9.783047
iter 31150: 9.839447
iter 31160: 9.739663
iter 31170: 9

iter 34600: 9.552349
iter 34610: 9.512619
iter 34620: 9.579562
iter 34630: 9.582552
iter 34640: 9.629060
iter 34650: 9.662447
iter 34660: 9.589035
iter 34670: 9.564877
iter 34680: 9.578325
iter 34690: 9.582157
iter 34700: 9.551721
iter 34710: 9.615252
iter 34720: 9.599950
iter 34730: 9.654078
iter 34740: 9.656865
iter 34750: 9.604518
iter 34760: 9.591835
iter 34770: 9.616890
iter 34780: 9.609876
iter 34790: 9.615274
iter 34800: 9.632116
iter 34810: 9.698593
iter 34820: 9.683331
iter 34830: 9.651445
iter 34840: 9.650772
iter 34850: 9.669540
iter 34860: 9.689992
iter 34870: 9.770467
iter 34880: 9.744247
iter 34890: 9.860405
iter 34900: 9.817660
iter 34910: 9.816388
iter 34920: 9.809285
iter 34930: 9.826729
iter 34940: 9.787341
iter 34950: 9.783576
iter 34960: 9.781410
iter 34970: 9.800915
iter 34980: 9.727424
iter 34990: 9.722179
iter 35000: 9.693849
iter 35010: 9.679731
iter 35020: 9.771718
iter 35030: 9.757183
iter 35040: 9.766005
iter 35050: 9.741416
iter 35060: 9.724473
iter 35070: 9

iter 38510: 9.382466
iter 38520: 9.403450
iter 38530: 9.362967
iter 38540: 9.376846
iter 38550: 9.418012
iter 38560: 9.393149
iter 38570: 9.359272
iter 38580: 9.378186
iter 38590: 9.267723
iter 38600: 9.290111
iter 38610: 9.332273
iter 38620: 9.383782
iter 38630: 9.301000
iter 38640: 9.384284
iter 38650: 9.399394
iter 38660: 9.361217
iter 38670: 9.358586
iter 38680: 9.347331
iter 38690: 9.334699
iter 38700: 9.378931
iter 38710: 9.328868
iter 38720: 9.407968
iter 38730: 9.472593
iter 38740: 9.494153
iter 38750: 9.544824
iter 38760: 9.661309
iter 38770: 9.616609
iter 38780: 9.604575
iter 38790: 9.586864
iter 38800: 9.583667
iter 38810: 9.558738
iter 38820: 9.559166
iter 38830: 9.511596
iter 38840: 9.510163
iter 38850: 9.574461
iter 38860: 9.569178
iter 38870: 9.604998
iter 38880: 9.623391
iter 38890: 9.636042
iter 38900: 9.652171
iter 38910: 9.681544
iter 38920: 9.705947
iter 38930: 9.733277
iter 38940: 9.736349
iter 38950: 9.748636
iter 38960: 9.743295
iter 38970: 9.739131
iter 38980: 9

## 4 Sentiment Analysis

In [9]:
!python q4_sentiment.py --yourvectors

Training for reg=0.000123
Train accuracy (%): 31.039326
Dev accuracy (%): 32.606721
Test accuracy (%): 30.497738
Training for reg=0.000204
Train accuracy (%): 31.051030
Dev accuracy (%): 32.515895
Test accuracy (%): 30.407240
Training for reg=0.000208
Train accuracy (%): 31.062734
Dev accuracy (%): 32.515895
Test accuracy (%): 30.271493
Training for reg=0.000529
Train accuracy (%): 31.156367
Dev accuracy (%): 32.606721
Test accuracy (%): 30.407240
Training for reg=0.000676
Train accuracy (%): 31.074438
Dev accuracy (%): 32.425068
Test accuracy (%): 30.316742
Training for reg=0.000860
Train accuracy (%): 31.168071
Dev accuracy (%): 32.697548
Test accuracy (%): 30.271493
Training for reg=0.001189
Train accuracy (%): 31.121255
Dev accuracy (%): 32.697548
Test accuracy (%): 30.361991
Training for reg=0.001352
Train accuracy (%): 31.214888
Dev accuracy (%): 32.425068
Test accuracy (%): 30.180995
Training for reg=0.001927
Train accuracy (%): 31.179775
Dev accuracy (%): 32.152589
Test accurac

In [10]:
!python q4_sentiment.py --pretrained

Training for reg=0.000101
Train accuracy (%): 39.899345
Dev accuracy (%): 36.330609
Test accuracy (%): 37.013575
Training for reg=0.000176
Train accuracy (%): 39.922753
Dev accuracy (%): 36.330609
Test accuracy (%): 36.968326
Training for reg=0.000717
Train accuracy (%): 39.922753
Dev accuracy (%): 36.512262
Test accuracy (%): 37.013575
Training for reg=0.001019
Train accuracy (%): 39.911049
Dev accuracy (%): 36.330609
Test accuracy (%): 37.058824
Training for reg=0.001290
Train accuracy (%): 39.887640
Dev accuracy (%): 36.512262
Test accuracy (%): 37.058824
Training for reg=0.001333
Train accuracy (%): 39.957865
Dev accuracy (%): 36.421435
Test accuracy (%): 36.968326
Training for reg=0.001506
Train accuracy (%): 39.922753
Dev accuracy (%): 36.421435
Test accuracy (%): 37.058824
Training for reg=0.002882
Train accuracy (%): 39.992978
Dev accuracy (%): 36.330609
Test accuracy (%): 37.013575
Training for reg=0.003273
Train accuracy (%): 39.946161
Dev accuracy (%): 36.330609
Test accurac